name: poke_list
description: Poke List

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  pokeapi: ^1.0.1
  http: ^0.12.2

dev_dependencies:
  build_runner:
  flutter_gen:
  flutter_test:
    sdk: flutter

flutter_gen:

flutter:

  uses-material-design: true

  assets:
    - assets/images/
